# FROM node:20
# WORKDIR /frontend/
# COPY ./package.json /frontend/package.json
# RUN npm install
# COPY ./tsconfig.json ./postcss.config.js ./tailwind.config.js ./tsconfig.node.json ./vite.config.ts ./index.html ./.eslintrc.cjs /frontend/
# COPY ./src/ /frontend/src/
# COPY ./public/ /frontend/public/
# CMD ["npm", "run", "dev", "--", "--host"]

# PROD Docker file
# PROD Docker file
# Stage 1: Build

FROM node:20-alpine AS builder

WORKDIR /app

# Copy package.json from root of build context (which is ./frontend)
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the frontend source
COPY . ./

RUN npm run build

# Stage 2
FROM node:20-alpine

WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist

EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]
