#!/bin/sh

cat <<EOF > /usr/share/nginx/html/env.js
window.env = {
  VITE_ENABLE_SSO: "${VITE_ENABLE_SSO}",
  VITE_FIRST_USER_EMAIL: "${VITE_FIRST_USER_EMAIL}",
  VITE_DOMAIN: "${VITE_DOMAIN}",
  VITE_URL_PREFIX: "${VITE_URL_PREFIX}",
  VITE_BACKEND_SSO_URL: "${VITE_BACKEND_SSO_URL}",
  VITE_BACKEND_THERMAX_GPT_URL: "${VITE_BACKEND_THERMAX_GPT_URL}",
  VITE_BACKEND_DOCTOR_CONBOT_URL: "${VITE_BACKEND_DOCTOR_CONBOT_URL}",
  VITE_BACKEND_TROUBLESHOOTING_URL: "${VITE_BACKEND_TROUBLESHOOTING_URL}",
  VITE_BACKEND_SALES_URL: "${VITE_BACKEND_SALES_URL}",
  VITE_BACKEND_TBWES_OCR_URL: "${VITE_BACKEND_TBWES_OCR_URL}"
};
EOF

exec nginx -g "daemon off;"