#!/bin/sh

cat <<EOF > /usr/share/nginx/html/env.js
window.env = {
  ENABLE_SSO: "${ENABLE_SSO}",
  ADMIN_USER_EMAIL: "${ADMIN_USER_EMAIL}",
  DOMAIN: "${DOMAIN}",
  URL_PREFIX: "${URL_PREFIX}",
  BACKEND_SSO_URL: "${BACKEND_SSO_URL}",
  BACKEND_THERMAX_GPT_URL: "${BACKEND_THERMAX_GPT_URL}",
  BACKEND_DOCTOR_CONBOT_URL: "${BACKEND_DOCTOR_CONBOT_URL}",
  BACKEND_SMART_TROUBLESHOOT_URL: "${BACKEND_SMART_TROUBLESHOOT_URL}",
  BACKEND_SALES_URL: "${BACKEND_SALES_URL}",
  BACKEND_TBWES_OCR_URL: "${BACKEND_TBWES_OCR_URL}"
};
EOF
exec nginx -g "daemon off;"