FROM node:20
WORKDIR /frontend

COPY ./package.json /frontend/package.json
RUN npm install

COPY ./tsconfig.json ./postcss.config.js ./tailwind.config.js ./tsconfig.node.json ./vite.config.ts ./index.html ./.eslintrc.cjs /frontend/
COPY ./src/ /frontend/src/
COPY ./public/ /frontend/public/

CMD ["npm", "run", "dev", "--", "--host"]
