version: '3.8'

services:
  frontend:
    container_name: thermax-frontend-local
    build:
      context: ../
      dockerfile: docker/Dockerfile.local
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_ENABLE_SSO: "${VITE_ENABLE_SSO}"
      VITE_FIRST_USER_EMAIL: "${VITE_FIRST_USER_EMAIL}"
      VITE_ADMIN_USER_EMAIL: "${VITE_ADMIN_USER_EMAIL}"
      VITE_DOMAIN: "${VITE_DOMAIN}"
      VITE_URL_PREFIX: "/thermax"
      VITE_BACKEND_SSO_URL: "${VITE_BACKEND_SSO_URL}"
      VITE_BACKEND_THERMAX_GPT_URL: "${VITE_BACKEND_THERMAX_GPT_URL}"
      VITE_BACKEND_DOCTOR_CONBOT_URL: "${VITE_BACKEND_DOCTOR_CONBOT_URL}"
      VITE_BACKEND_SMART_TROUBLESHOOT_URL: "${VITE_BACKEND_SMART_TROUBLESHOOT_URL}"
      VITE_BACKEND_SALES_URL: "${VITE_BACKEND_SALES_URL}"
      VITE_BACKEND_TBWES_OCR_URL: "${VITE_BACKEND_TBWES_OCR_URL}"
      VITE_BACKEND_CYBERBUDDY_URL: "${VITE_BACKEND_CYBERBUDDY_URL}"
      VITE_BACKEND_HEATING_OCR_URL: "${VITE_BACKEND_HEATING_OCR_URL}"
      VITE_BACKEND_EDGE_URL: "${VITE_BACKEND_EDGE_URL}"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ../frontend/src:/frontend/src
      - ../frontend/public:/frontend/public
    env_file:
      - ../frontend/.env

networks:
  default:
    external:
      name: thermax-network
