version: '3.8'

services:
  frontend:
    container_name: thermax-frontend-local
    build:
      context: ../
      dockerfile: docker/Dockerfile.local
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_ENABLE_SSO: "${ENABLE_SSO}"
      VITE_FIRST_USER_EMAIL: "${FIRST_USER_EMAIL}"
      VITE_ADMIN_USER_EMAIL: "${ADMIN_USER_EMAIL}"
      VITE_DOMAIN: "${DOMAIN}"
      VITE_URL_PREFIX: "/thermax"
      VITE_THERMAX_GPT: "${THERMAX_GPT}"
      VITE_SALES: "${SALES}"
      VITE_TBWES_OCR: "${TBWES_OCR}"
      VITE_SMART_TROUBLESHOOT: "${SMART_TROUBLESHOOT}"
      VITE_DOCTOR_CONBOT: "${DOCTOR_CONBOT}"
      VITE_CYBERBUDDY: "${CYBERBUDDY}"
      VITE_HEATING_OCR: "${HEATING_OCR}"
      VITE_BACKEND_SSO_URL: "${BACKEND_SERVICE_SSO_URL}"
      VITE_BACKEND_THERMAX_GPT_URL: "${BACKEND_SERVICE_THERMAX_GPT_URL}"
      VITE_BACKEND_DOCTOR_CONBOT_URL: "${BACKEND_SERVICE_DOCTOR_CONBOT_URL}"
      VITE_BACKEND_TROUBLESHOOTING_URL: "${BACKEND_SERVICE_SMART_TROUBLESHOOT_URL}"
      VITE_BACKEND_SALES_URL: "${BACKEND_SERVICE_SALES_URL}"
      VITE_BACKEND_TBWES_OCR_URL: "${BACKEND_SERVICE_TBWES_OCR_URL}"
      VITE_BACKEND_CYBERBUDDY_URL: "${BACKEND_SERVICE_CYBERBUDDY_URL}"
      VITE_BACKEND_HEATING_OCR_URL: "${BACKEND_SERVICE_HEATING_OCR_URL}"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ../frontend/src:/frontend/src
      - ../frontend/public:/frontend/public
    env_file:
      - ../frontend/.env

networks:
  default:
    external:
      name: thermax-network
