version: "3.8"

services:
  frontend:
    container_name: thermax-frontend-staging
    build:
      context: .
      dockerfile: ./docker/Dockerfile.staging
      args:
        VITE_ENABLE_SSO: "true"
        VITE_ADMIN_USER_EMAIL: "admin@example.com"
        VITE_DOMAIN: "staging.thermax.thoughtmlabs.com"
        VITE_URL_PREFIX: "/thermax"
        VITE_BACKEND_SSO_URL: "http://sso-service:3001/api"
        VITE_BACKEND_THERMAX_GPT_URL: "http://gpt-service:3002/api"
        VITE_BACKEND_DOCTOR_CONBOT_URL: "http://doctor-service:3003/api"
        VITE_BACKEND_SMART_TROUBLESHOOT_URL: "http://troubleshoot-service:3004/api"
        VITE_BACKEND_SALES_URL: "http://sales-service:3005/api"
        VITE_BACKEND_TBWES_OCR_URL: "http://ocr-service:3006/api"
        VITE_BACKEND_CYBERBUDDY_URL: "http://cyberbuddy-service:3007/api"
        VITE_BACKEND_HEATING_OCR_URL: "http://heating-ocr-service:3008/api"
        VITE_BACKEND_EDGE_URL: "http://edge-service:3009/api"
        VITE_BACKEND_TRANSMITTER_OCR_URL: "http://transmitter-ocr-service:3009"
        VITE_BACKEND_DOCUMENT_TRANSLATOR_URL: "http://sales-service:3005/api"
        VITE_BACKEND_CCTV_ANALYTICS_URL: "https://sitesafety.azcinp.thermaxglobal.com/super-admin/dashboard"
        VITE_BACKEND_PRICING_ANALYTICS_URL: "http://pricing-analytics-service:3010/api"
    ports:
      - "3000:80"
    restart: unless-stopped
