
worker_processes auto;

events {
}

http {
    client_max_body_size 50M;
    include /etc/nginx/mime.types;
    # upstream api_backend{
    #     server backend:9000;
    # }
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
        location = /50x.html {
            root /usr/share/nginx/html;
        }
        # location /api {
        #     proxy_pass http://api_backend;
        # }
    }

}
