name: Prod Deployment - Thermax Frontend Deployment

on:
  push:
    branches:
      - master

env:
  ACR_NAME: ${{ vars.PROD_ACR_NAME }}
  IMAGE_NAME: thermax_frontend
  RESOURCE_GROUP: ${{ vars.PROD_RESOURCE_GROUP }}
  CONTAINER_APP_NAME: ${{ vars.PROD_CONTAINER_APP_NAME }}
  IMAGE_TAG: prod-${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.prod \
            --build-arg VITE_ENABLE_SSO="${{ vars.VITE_ENABLE_SSO }}" \
            --build-arg VITE_ADMIN_USER_EMAIL="${{ secrets.VITE_ADMIN_USER_EMAIL }}" \
            --build-arg VITE_DOMAIN="${{ vars.VITE_DOMAIN }}" \
            --build-arg VITE_URL_PREFIX="${{ vars.VITE_URL_PREFIX }}" \
            --build-arg VITE_BACKEND_SSO_URL="${{ secrets.VITE_BACKEND_SSO_URL }}" \
            --build-arg VITE_BACKEND_THERMAX_GPT_URL="${{ secrets.VITE_BACKEND_THERMAX_GPT_URL }}" \
            --build-arg VITE_BACKEND_DOCTOR_CONBOT_URL="${{ secrets.VITE_BACKEND_DOCTOR_CONBOT_URL }}" \
            --build-arg VITE_BACKEND_SMART_TROUBLESHOOT_URL="${{ secrets.VITE_BACKEND_SMART_TROUBLESHOOT_URL }}" \
            --build-arg VITE_BACKEND_SALES_URL="${{ secrets.VITE_BACKEND_SALES_URL }}" \
            --build-arg VITE_BACKEND_TBWES_OCR_URL="${{ secrets.VITE_BACKEND_TBWES_OCR_URL }}" \
            --build-arg VITE_BACKEND_CYBERBUDDY_URL="${{ secrets.VITE_BACKEND_CYBERBUDDY_URL }}" \
            --build-arg VITE_BACKEND_HEATING_OCR_URL="${{ secrets.VITE_BACKEND_HEATING_OCR_URL }}" \
            --build-arg VITE_BACKEND_TRANSMITTER_OCR_URL="${{ secrets.VITE_BACKEND_TRANSMITTER_OCR_URL }}" \
            --build-arg VITE_BACKEND_DOCUMENT_TRANSLATOR_URL="${{ secrets.VITE_BACKEND_DOCUMENT_TRANSLATOR_URL }}" \
            --build-arg VITE_BACKEND_EDGE_URL="${{ secrets.VITE_BACKEND_EDGE_URL }}" \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to Prod ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to Azure Container App (Production)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
