name: Staging Deployment - Thermax Frontend Deployment

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type YES to deploy'
        required: true

permissions:
  contents: write

env:
  ACR_NAME:  ${{ vars.STAGING_ACR_NAME }}
  IMAGE_NAME: thermax_frontend
  RESOURCE_GROUP: ${{ vars.STAGING_RESOURCE_GROUP }}
  CONTAINER_APP_NAME: ${{ vars.STAGING_CONTAINER_APP_NAME }}
  IMAGE_TAG: staging-${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print variables
        run: |
          echo "ACR_NAME: $ACR_NAME"
          echo "RESOURCE_GROUP: $RESOURCE_GROUP"
          echo "CONTAINER_APP_NAME: $CONTAINER_APP_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"

      - name: Log in to Staging ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.staging \
            --build-arg VITE_ENABLE_SSO="${{ vars.VITE_ENABLE_SSO }}" \
            --build-arg VITE_ADMIN_USER_EMAIL="${{ secrets.VITE_ADMIN_USER_EMAIL }}" \
            --build-arg VITE_DOMAIN="${{ vars.VITE_DOMAIN }}" \
            --build-arg VITE_URL_PREFIX="${{ vars.VITE_URL_PREFIX }}" \
            --build-arg VITE_BACKEND_SSO_URL="${{ secrets.VITE_BACKEND_SSO_URL }}" \
            --build-arg VITE_BACKEND_THERMAX_GPT_URL="${{ secrets.VITE_BACKEND_THERMAX_GPT_URL }}" \
            --build-arg VITE_BACKEND_DOCTOR_CONBOT_URL="${{ secrets.VITE_BACKEND_DOCTOR_CONBOT_URL }}" \
            --build-arg VITE_BACKEND_SMART_TROUBLESHOOT_URL="${{ secrets.VITE_BACKEND_SMART_TROUBLESHOOT_URL }}" \
            --build-arg VITE_BACKEND_SALES_URL="${{ secrets.VITE_BACKEND_SALES_URL }}" \
            --build-arg VITE_BACKEND_TBWES_OCR_URL="${{ secrets.VITE_BACKEND_TBWES_OCR_URL }}" \
            --build-arg VITE_BACKEND_CYBERBUDDY_URL="${{ secrets.VITE_BACKEND_CYBERBUDDY_URL }}" \
            --build-arg VITE_BACKEND_HEATING_OCR_URL="${{ secrets.VITE_BACKEND_HEATING_OCR_URL }}" \
            --build-arg VITE_BACKEND_TRANSMITTER_OCR_URL="${{ secrets.VITE_BACKEND_TRANSMITTER_OCR_URL }}" \
            --build-arg VITE_BACKEND_DOCUMENT_TRANSLATOR_URL="${{ secrets.VITE_BACKEND_DOCUMENT_TRANSLATOR_URL }}" \
            --build-arg VITE_BACKEND_EDGE_URL="${{ secrets.VITE_BACKEND_EDGE_URL }}" \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to Staging ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to Azure Container App (Staging)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG


      - name: Create and Push Git Tag for Staging
        if: success()
        run: |
          TAG_NAME=staging-${{ github.run_number }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
          git tag $TAG_NAME
          git push origin $TAG_NAME
          